export type SiteLocale = 'en' | 'id'

export const landCopy = {
  en: {
    nav: { site: 'The site', uses: 'Plot options', location: 'Nearby', evidence: 'Market notes', brief: 'Request brochure' },
    kicker: 'Commercial land · Berawa',
    years: '30 years',
    hero: 'Lease a 4–6 are plot or the full 25 are beside Mosto on Jalan Pantai Berawa.',
    primary: 'Request brochure',
    explore: 'View plot options',
    facts: [['Land area', '2,500 sqm'], ['Lease term', '30 years'], ['Address', 'Berawa 1053'], ['Status', 'Expressions of interest']],
    siteLabel: 'The site · one continuous holding',
    siteTitle: 'The land and its location.',
    siteHeading: 'Lease the whole site or discuss a smaller plot.',
    siteBody: 'The supplied aerial view shows the approximately 25-are area in relation to Jalan Pantai Berawa and the surrounding hospitality neighbourhood.',
    parcelDisclaimer: 'Indicative site location and outline supplied by the owner. Not a cadastral survey, title plan, or representation of legal boundaries, frontage or access.',
    mapSiteLabel: 'Indicative 25-are area',
    mapSiteMeta: '2,500 sqm · 30-year lease',
    mapLegend: [['The site', 'Owner-supplied indicative outline'], ['BERAWA 1053', 'Existing commercial address'], ['Near Mosto', 'Established dining destination'], ['Jalan Pantai Berawa', 'Main Berawa corridor']],
    sitePoints: ['30-year lease structure', 'Near an established premium dining anchor', 'Existing BERAWA 1053 commercial identity', 'Use flexibility, subject to verified zoning and permits'],
    dataCta: 'Request brochure',
    usesLabel: 'The tenant thesis',
    usesTitle: 'A full-day mix, not one more copy.',
    usesIntro: 'The strongest use creates reasons to arrive from morning through evening and complements Berawa’s established operators.',
    uses: [
      ['Morning', 'Clinical & performance wellness', 'Recovery, physio, diagnostics, aesthetics and specialist care with repeat local demand.'],
      ['Day', 'Family & enrichment', 'Early learning, indoor play, creative programmes and a family-oriented café offer.'],
      ['Afternoon', 'Flagship retail & showrooms', 'Resortwear, interiors, surf, mobility and hospitality brands with destination appeal.'],
      ['Evening', 'Food-led lifestyle anchor', 'A curated market, all-day restaurant or culinary compound that complements Mosto.'],
    ],
    proofLabel: 'Adjacent proof of place',
    proofTitle: 'A real address. Real material.',
    proofBody: 'These images show the completed BERAWA 1053 commercial building beside the opportunity. They do not represent improvements on the 25-are parcel.',
    imageLabels: ['Completed neighbour · frontage', 'Existing commercial quality', 'Material identity'],
    dueDiligence: 'All concepts remain subject to legal, zoning, access, survey, utility and technical due diligence.',
    addressLabel: 'The address',
    addressBody: 'Near Mosto on the Berawa corridor, within the wider beach, hospitality, dining and residential ecosystem.',
    mapCta: 'Open in Google Maps',
    mapTitle: 'Google Map of BERAWA 1053',
    mapDisclaimer: 'The pin shows the supplied site location for orientation only. Parcel boundaries, frontage and access are subject to survey and title verification.',
    evidenceLabel: 'Source-backed market notes',
    evidenceTitle: 'Read the growth. Keep the caveats.',
    evidenceBody: 'Historical context for operators evaluating a long-term Berawa decision, built from official statistics and clearly dated sources.',
    readArticle: 'Read article',
    termsLabel: 'Proposed transaction',
    termsTitle: 'Simple lease starting points.',
    terms: [
      ['Term', '30-year lease, documented by an Indonesian notary.'],
      ['Plot size', 'Whole 25 are or smaller plots of approximately 4 to 6 are.'],
      ['Pricing', 'Price and payment options are shared on enquiry.'],
      ['Checks', 'Confirm title, measured area, zoning, access and utilities before contract.'],
    ],
    disclaimer: 'Marketing information only. This page is not legal, tax, valuation or investment advice. Facts and permitted use must be independently verified before contract.',
    formLabel: 'Qualified enquiries',
    formTitle: 'Request the brochure.',
    formBody: 'Tell us your preferred plot size and intended use. We will send the brochure and arrange a site visit.',
    fields: { name: 'Your name', company: 'Company', concept: 'Intended use or concept', timeline: 'Decision timeline', timelineOptions: ['Select one', '0–3 months', '3–6 months', '6–12 months', '12+ months'] },
    send: 'Continue on WhatsApp',
    email: 'Email instead',
    formNote: 'Submitting opens WhatsApp with your answers. No data is stored on this website.',
    footer: 'Long-lease commercial land · Bali',
    shops: 'Existing shops',
    blog: 'Market notes',
  },
  id: {
    nav: { site: 'Lahan', uses: 'Pilihan bidang', location: 'Sekitar', evidence: 'Catatan pasar', brief: 'Minta brosur' },
    kicker: 'Lahan komersial · Berawa',
    years: '30 tahun',
    hero: 'Sewa bidang 4–6 are atau seluruh 25 are di sebelah Mosto, Jalan Pantai Berawa.',
    primary: 'Minta brosur',
    explore: 'Lihat pilihan bidang',
    facts: [['Luas lahan', '2.500 m²'], ['Masa sewa', '30 tahun'], ['Alamat', 'Berawa 1053'], ['Status', 'Menerima minat']],
    siteLabel: 'Lahan · satu kesatuan',
    siteTitle: 'Lahan dan lokasinya.',
    siteHeading: 'Sewa seluruh lahan atau bahas bidang yang lebih kecil.',
    siteBody: 'Tampilan udara yang diberikan menunjukkan area sekitar 25 are dalam hubungannya dengan Jalan Pantai Berawa dan lingkungan hospitality di sekitarnya.',
    parcelDisclaimer: 'Lokasi dan garis lahan indikatif diberikan oleh pemilik. Bukan survei kadastral, denah sertifikat, atau pernyataan batas hukum, fasad maupun akses.',
    mapSiteLabel: 'Area indikatif 25 are',
    mapSiteMeta: '2.500 m² · sewa 30 tahun',
    mapLegend: [['Lahan', 'Garis indikatif dari pemilik'], ['BERAWA 1053', 'Alamat komersial yang sudah ada'], ['Dekat Mosto', 'Destinasi kuliner yang sudah dikenal'], ['Jalan Pantai Berawa', 'Koridor utama Berawa']],
    sitePoints: ['Struktur sewa 30 tahun', 'Dekat destinasi kuliner premium', 'Identitas komersial BERAWA 1053 sudah ada', 'Fleksibilitas penggunaan, tergantung zonasi dan izin terverifikasi'],
    dataCta: 'Minta brosur',
    usesLabel: 'Tesis penyewa',
    usesTitle: 'Aktif sepanjang hari, bukan sekadar meniru.',
    usesIntro: 'Penggunaan terbaik memberi alasan untuk datang dari pagi hingga malam dan melengkapi operator Berawa yang sudah ada.',
    uses: [
      ['Pagi', 'Wellness klinis & performa', 'Pemulihan, fisioterapi, diagnostik, estetika dan perawatan spesialis dengan permintaan lokal berulang.'],
      ['Siang', 'Keluarga & pengayaan', 'Pendidikan dini, area bermain indoor, program kreatif dan kafe ramah keluarga.'],
      ['Sore', 'Retail flagship & showroom', 'Resortwear, interior, surf, mobilitas dan brand hospitality yang menjadi destinasi.'],
      ['Malam', 'Destinasi lifestyle berbasis kuliner', 'Pasar terkurasi, restoran sepanjang hari atau kompleks kuliner yang melengkapi Mosto.'],
    ],
    proofLabel: 'Bukti lokasi di sebelah',
    proofTitle: 'Alamat nyata. Material nyata.',
    proofBody: 'Foto ini menampilkan bangunan komersial BERAWA 1053 yang telah selesai di sebelah peluang lahan. Foto bukan gambaran bangunan di atas lahan 25 are.',
    imageLabels: ['Bangunan sebelah · fasad', 'Kualitas komersial yang ada', 'Identitas material'],
    dueDiligence: 'Semua konsep tergantung uji tuntas hukum, zonasi, akses, survei, utilitas dan teknis.',
    addressLabel: 'Alamat',
    addressBody: 'Dekat Mosto di koridor Berawa, dalam ekosistem pantai, hotel, kuliner dan hunian.',
    mapCta: 'Buka di Google Maps',
    mapTitle: 'Peta Google BERAWA 1053',
    mapDisclaimer: 'Pin menunjukkan lokasi yang diberikan untuk orientasi saja. Batas bidang, fasad dan akses harus diverifikasi melalui survei dan sertifikat.',
    evidenceLabel: 'Catatan pasar bersumber',
    evidenceTitle: 'Baca pertumbuhannya. Pahami catatannya.',
    evidenceBody: 'Konteks historis bagi operator yang mengevaluasi keputusan jangka panjang di Berawa, berdasarkan statistik resmi dan sumber bertanggal jelas.',
    readArticle: 'Baca artikel',
    termsLabel: 'Transaksi yang diusulkan',
    termsTitle: 'Titik awal sewa yang sederhana.',
    terms: [
      ['Jangka waktu', 'Sewa 30 tahun, didokumentasikan oleh notaris Indonesia.'],
      ['Ukuran bidang', 'Seluruh 25 are atau bidang lebih kecil sekitar 4 sampai 6 are.'],
      ['Harga', 'Harga dan pilihan pembayaran dibagikan saat ada pertanyaan.'],
      ['Pemeriksaan', 'Verifikasi sertifikat, luas terukur, zonasi, akses dan utilitas sebelum kontrak.'],
    ],
    disclaimer: 'Informasi pemasaran saja. Halaman ini bukan nasihat hukum, pajak, valuasi atau investasi. Fakta dan penggunaan yang diizinkan harus diverifikasi secara independen sebelum kontrak.',
    formLabel: 'Pertanyaan terverifikasi',
    formTitle: 'Minta brosur.',
    formBody: 'Beritahu ukuran bidang dan rencana penggunaan. Kami akan mengirimkan brosur dan mengatur kunjungan lokasi.',
    fields: { name: 'Nama Anda', company: 'Perusahaan', concept: 'Rencana penggunaan atau konsep', timeline: 'Waktu keputusan', timelineOptions: ['Pilih satu', '0–3 bulan', '3–6 bulan', '6–12 bulan', '12+ bulan'] },
    send: 'Lanjutkan di WhatsApp',
    email: 'Gunakan email',
    formNote: 'Tombol akan membuka WhatsApp dengan jawaban Anda. Tidak ada data yang disimpan di situs ini.',
    footer: 'Sewa lahan komersial jangka panjang · Bali',
    shops: 'Ruko yang ada',
    blog: 'Catatan pasar',
  },
} as const

export function asSiteLocale(locale: string): SiteLocale {
  return locale === 'id' ? 'id' : 'en'
}
